global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'app-monitor'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'prometheus:9090' ]

  - job_name: 'telegraf'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'telegraf:9100' ]

  - job_name: 'api'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'api:8001' ]
